image: node:alpine

pages:
  stage: deploy
  script:
    - npm install -g sass
    - sass public/css/styles.scss public/css/styles.css
    - echo "Site will be deployed to $CI_PAGES_URL"
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
